// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PruebaLucasFelizDGII.Models;

#nullable disable

namespace PruebaLucasFelizDGII.Migrations
{
    [DbContext(typeof(DGIIDbContext))]
    partial class DGIIDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PruebaLucasFelizDGII.Models.Comprobantes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Itbis18")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("NCF")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("RNCCedula")
                        .HasColumnType("bigint");

                    b.Property<int>("contribuyenteId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("contribuyenteId");

                    b.ToTable("Comprobantes");
                });

            modelBuilder.Entity("PruebaLucasFelizDGII.Models.Contribuyentes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Estatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("RNCCedula")
                        .HasColumnType("bigint");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Contribuyentes");
                });

            modelBuilder.Entity("PruebaLucasFelizDGII.Models.Comprobantes", b =>
                {
                    b.HasOne("PruebaLucasFelizDGII.Models.Contribuyentes", "contribuyente")
                        .WithMany()
                        .HasForeignKey("contribuyenteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("contribuyente");
                });
#pragma warning restore 612, 618
        }
    }
}
